# Challenge 1

In this challenge you will be working on **Pokemon**. You will answer a series of questions in order to practice dataframe calculation, aggregation, and transformation.

![Pokemon](../images/pokemon.jpg)

Follow the instructions below and enter your code.

#### Import all required libraries.

In [2]:
# import libraries
import numpy as np
import pandas as pd
import json
%pip install xlrd
%pip install openpyxl

Requirement already satisfied: xlrd in c:\users\veronica\anaconda3\lib\site-packages (2.0.1)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: openpyxl in c:\users\veronica\anaconda3\lib\site-packages (3.0.10)
Requirement already satisfied: et_xmlfile in c:\users\veronica\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

#### Import data set.

Import data set `Pokemon` from Ironhack's database. Read the data into a dataframe called `pokemon`.

*Data set attributed to [Alberto Barradas](https://www.kaggle.com/abcsds/pokemon/)*

In [3]:
# import data set from Ironhack's database
Pokemon =pd.read_csv('pokemon.csv')

Pokemon.columns = [e.replace(' ', '_').lower() for e in Pokemon.columns]

#### Print first 10 rows of `pokemon`.

In [4]:
# your code here
Pokemon.head(10)

,#,name,type_1,type_2,total,hp,attack,defense,sp._atk,sp._def,speed,generation,legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

When you look at a data set, you often wonder what each column means. Some open-source data sets provide descriptions of the data set. In many cases, data descriptions are extremely useful for data analysts to perform work efficiently and successfully.

For the `Pokemon.csv` data set, fortunately, the owner provided descriptions which you can see [here](https://www.kaggle.com/abcsds/pokemon/home). For your convenience, we are including the descriptions below. Read the descriptions and understand what each column means. This knowledge is helpful in your work with the data.

| Column | Description |
| --- | --- |
| # | ID for each pokemon |
| Name | Name of each pokemon |
| Type 1 | Each pokemon has a type, this determines weakness/resistance to attacks |
| Type 2 | Some pokemon are dual type and have 2 |
| Total | A general guide to how strong a pokemon is |
| HP | Hit points, or health, defines how much damage a pokemon can withstand before fainting |
| Attack | The base modifier for normal attacks (eg. Scratch, Punch) |
| Defense | The base damage resistance against normal attacks |
| SP Atk | Special attack, the base modifier for special attacks (e.g. fire blast, bubble beam) |
| SP Def | The base damage resistance against special attacks |
| Speed | Determines which pokemon attacks first each round |
| Generation | Number of generation |
| Legendary | True if Legendary Pokemon False if not |

#### Obtain the distinct values across `Type 1` and `Type 2`.

Exctract all the values in `Type 1` and `Type 2`. Then create an array containing the distinct values across both fields.

In [5]:

unique_values = pd.unique(pd.concat([Pokemon['type_1'], Pokemon['type_2']]))
unique_values

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying', nan], dtype=object)

In [6]:
np.array(list((set(Pokemon['type_1'].unique().tolist()+Pokemon['type_1'].unique().tolist()))))

array(['Poison', 'Water', 'Fairy', 'Flying', 'Ground', 'Rock', 'Ghost',
       'Dragon', 'Psychic', 'Normal', 'Steel', 'Dark', 'Ice', 'Fire',
       'Fighting', 'Electric', 'Bug', 'Grass'], dtype='<U8')

#### Cleanup `Name` that contain "Mega".

If you have checked out the pokemon names carefully enough, you should have found there are junk texts in the pokemon names which contain "Mega". We want to clean up the pokemon names. For instance, "VenusaurMega Venusaur" should be "Mega Venusaur", and "CharizardMega Charizard X" should be "Mega Charizard X".

In [7]:
Pokemon.name[Pokemon.name.str.contains('Mega ')]

3          VenusaurMega Venusaur
7      CharizardMega Charizard X
8      CharizardMega Charizard Y
12       BlastoiseMega Blastoise
19         BeedrillMega Beedrill
23           PidgeotMega Pidgeot
71         AlakazamMega Alakazam
87           SlowbroMega Slowbro
102            GengarMega Gengar
124    KangaskhanMega Kangaskhan
137            PinsirMega Pinsir
141        GyaradosMega Gyarados
154    AerodactylMega Aerodactyl
163          MewtwoMega Mewtwo X
164          MewtwoMega Mewtwo Y
196        AmpharosMega Ampharos
224          SteelixMega Steelix
229            ScizorMega Scizor
232      HeracrossMega Heracross
248        HoundoomMega Houndoom
268      TyranitarMega Tyranitar
275        SceptileMega Sceptile
279        BlazikenMega Blaziken
283        SwampertMega Swampert
306      GardevoirMega Gardevoir
327          SableyeMega Sableye
329            MawileMega Mawile
333            AggronMega Aggron
336        MedichamMega Medicham
339      ManectricMega Manectric
349        SharpedoMega Sharpedo
354        CameruptMega Camerupt
366          AltariaMega Altaria
387          BanetteMega Banette
393              AbsolMega Absol
397            GlalieMega Glalie
409      SalamenceMega Salamence
413      MetagrossMega Metagross
418            LatiasMega Latias
420            LatiosMega Latios
426        RayquazaMega Rayquaza
476          LopunnyMega Lopunny
494        GarchompMega Garchomp
498          LucarioMega Lucario
511      AbomasnowMega Abomasnow
527          GalladeMega Gallade
591            AudinoMega Audino
796          DiancieMega Diancie
Name: name, dtype: object

In [8]:
# your code here

Pokemon.name=Pokemon.name.apply(lambda s: 'Mega '+s.split('Mega ')[1] if 'Mega ' in s else s)

    
[e for e in Pokemon.name.unique() if 'Mega' in e]
# test transformed data

['Mega Venusaur',
 'Mega Charizard X',
 'Mega Charizard Y',
 'Mega Blastoise',
 'Mega Beedrill',
 'Mega Pidgeot',
 'Mega Alakazam',
 'Mega Slowbro',
 'Mega Gengar',
 'Mega Kangaskhan',
 'Mega Pinsir',
 'Mega Gyarados',
 'Mega Aerodactyl',
 'Mega Mewtwo X',
 'Mega Mewtwo Y',
 'Meganium',
 'Mega Ampharos',
 'Mega Steelix',
 'Mega Scizor',
 'Mega Heracross',
 'Mega Houndoom',
 'Mega Tyranitar',
 'Mega Sceptile',
 'Mega Blaziken',
 'Mega Swampert',
 'Mega Gardevoir',
 'Mega Sableye',
 'Mega Mawile',
 'Mega Aggron',
 'Mega Medicham',
 'Mega Manectric',
 'Mega Sharpedo',
 'Mega Camerupt',
 'Mega Altaria',
 'Mega Banette',
 'Mega Absol',
 'Mega Glalie',
 'Mega Salamence',
 'Mega Metagross',
 'Mega Latias',
 'Mega Latios',
 'Mega Rayquaza',
 'Mega Lopunny',
 'Mega Garchomp',
 'Mega Lucario',
 'Mega Abomasnow',
 'Mega Gallade',
 'Mega Audino',
 'Mega Diancie']

#### Create a new column called `A/D Ratio` whose value equals to `Attack` devided by `Defense`.

For instance, if a pokemon has the Attack score 49 and Defense score 49, the corresponding `A/D Ratio` is 49/49=1.

In [9]:
# your code here
Pokemon['A/D Ratio']=Pokemon['attack']/Pokemon['defense']
Pokemon['A/D Ratio']=Pokemon['A/D Ratio'].round(2)

Pokemon.head()

,#,name,type_1,type_2,total,hp,attack,defense,sp._atk,sp._def,speed,generation,legendary,A/D Ratio
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.00
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.98
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.99
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.81
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.21

#### Identify the pokemon with the highest `A/D Ratio`.

In [10]:
# your code here
Pokemon[Pokemon['A/D Ratio']==Pokemon['A/D Ratio'].max()]

,#,name,type_1,type_2,total,hp,attack,defense,sp._atk,sp._def,speed,generation,legendary,A/D Ratio
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.0

#### Identify the pokemon with the lowest A/D Ratio.

In [11]:
# your code here
Pokemon[Pokemon['A/D Ratio']==Pokemon['A/D Ratio'].min()]

,#,name,type_1,type_2,total,hp,attack,defense,sp._atk,sp._def,speed,generation,legendary,A/D Ratio
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False,0.04

### Create a new column called `Combo Type` whose value combines `Type 1` and `Type 2`.

Rules:

* If both `Type 1` and `Type 2` have valid values, the `Combo Type` value should contain both values in the form of `<Type 1> <Type 2>`. For example, if `Type 1` value is `Grass` and `Type 2` value is `Poison`, `Combo Type` will be `Grass-Poison`.

* If `Type 1` has valid value but `Type 2` is not, `Combo Type` will be the same as `Type 1`. For example, if `Type 1` is `Fire` whereas `Type 2` is `NaN`, `Combo Type` will be `Fire`.

In [12]:
Pokemon['Combo Type'] = Pokemon['type_1']+ '-'+Pokemon['type_2']
Pokemon.loc[Pokemon[Pokemon['type_2'].isna()].index,'Combo Type'] = Pokemon[Pokemon['type_2'].isna()].type_1
Pokemon

,#,name,type_1,type_2,total,hp,attack,defense,sp._atk,sp._def,speed,generation,legendary,A/D Ratio,Combo Type
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.00,Grass-Poison
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.98,Grass-Poison
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.99,Grass-Poison
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.81,Grass-Poison
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.21,Fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,0.67,Rock-Fairy
796,719,Mega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1.45,Rock-Fairy
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,1.83,Psychic-Ghost
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,2.67,Psychic-Dark
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,0.92,Fire-Water

#### Identify the pokemon whose `A/D Ratio` are among the top 5.

In [13]:
# your code here
Pokemon.sort_values(by='A/D Ratio', ascending=False).head(5)

,#,name,type_1,type_2,total,hp,attack,defense,sp._atk,sp._def,speed,generation,legendary,A/D Ratio,Combo Type
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.00,Psychic
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.50,Water-Dark
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.75,Bug-Poison
453,408,Cranidos,Rock,NaN,350,67,125,40,30,30,58,4,False,3.12,Rock
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.00,Water-Dark

#### For the 5 pokemon printed above, aggregate `Combo Type` and use a list to store the unique values.

Your end product is a list containing the distinct `Combo Type` values of the 5 pokemon with the highest `A/D Ratio`.

In [14]:
# your code here
lst=Pokemon.sort_values(by='A/D Ratio', ascending=False).head(5)['Combo Type'].tolist()
lst

['Psychic', 'Water-Dark', 'Bug-Poison', 'Rock', 'Water-Dark']

#### For each of the `Combo Type` values obtained from the previous question, calculate the mean scores of all numeric fields across all pokemon.

Your output should look like below:

![Aggregate](../images/aggregated-mean.png)

In [17]:
# your code here
Pokemon.groupby('Combo Type').mean(numeric_only=True).head()

,#,total,hp,attack,defense,sp._atk,sp._def,speed,generation,legendary,A/D Ratio
Combo Type,,,,,,,,,,,
Bug,361.352941,289.705882,53.058824,50.352941,55.411765,39.294118,43.647059,47.941176,3.470588,0.0,0.941176
Bug-Electric,595.500000,395.500000,60.000000,62.000000,55.000000,77.000000,55.000000,86.500000,5.000000,0.0,1.110000
Bug-Fighting,214.000000,550.000000,80.000000,155.000000,95.000000,40.000000,100.000000,80.000000,2.000000,0.0,1.640000
Bug-Fire,636.500000,455.000000,70.000000,72.500000,60.000000,92.500000,80.000000,80.000000,5.000000,0.0,1.235000
Bug-Flying,286.285714,419.500000,63.000000,70.142857,61.571429,72.857143,69.071429,82.857143,2.857143,0.0,1.145714